### ISSUE TITLE
Accessories visible but cannot pair

### ISSUE THREAD

**Issue by mcuthbert** [KhaosT/HAP-NodeJS#273]
Greetings!
I have a successful setup at home with a raspberry pi, but I am on the road at the moment and attempting to setup a test platform using VMware and HAP running on a virtual OSx Yosemite setup.  I have it up and running, accessories are visible on the Home app (iOS 10) but when I go to add them after entering the pin it thinks then responds that the accessory cannot be found.  Running Core.js with debug gives me the following:

Parsing accessory: TemperatureSensor_accessory.js
  EventedHTTPServer Server listening on port 51826 +0ms
  EventedHTTPServer [::ffff:127.0.0.1] New connection from client +1m
  EventedHTTPServer [::ffff:127.0.0.1] HTTP server listening on port 49267 +1ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP request: / +14ms
  HAPServer [C1:5D:3A:AE:5E:FA] HAP Request: GET / +1ms
  HAPServer [C1:5D:3A:AE:5E:FA] WARNING: Handler for / not implemented +2ms
  EventedHTTPServer [::ffff:127.0.0.1] HTTP Response is finished +3ms

Any clues as to where the issue lies?  I have some Sonoff units arriving shortly that I will flash to Nodemcu and deploy - I need to get my testbed up and running ASAP.

Thank you for this great project!

Regards,
Michael

**Comment by KhaosT** [comment]
Are you sure this is unmodified iOS? iOS should not send GET request to accessory requesting "/"

**Comment by mcuthbert** [comment]
100% sure - iOS beta 10, i wish I was at home with a known working setup to try and trouble shoot this. I'"" have to wait 2 months if I can't get this working 😔

**Comment by mcuthbert** [comment]
For info I tried accessing the accessories on an iPad mini with iOS 9.3 through idevice, I didn't get the option to enter a pin - the devices just disappeared as if they'd been added. I have also tried stripping out all of the accessory files and leaving just one - I tried the temperature sensor and garage door, no joy. Thank you for your quick reply, is there any other way to get logs that might help other than run debug?

**Comment by KhaosT** [comment]
If you're on iOS 10 + macOS Sierra, you can try to use Console.app on macOS and get HomeKit log so I can figure out why iOS is doing this. Without log, I'm afraid there isn't a lot I can do.

**Comment by mcuthbert** [comment]
All, this issue has been solved.  I'm still diagnosing the exact cause but it is a network issue on the wireless network I am on.  Possibly a firewall on the router?  Anyway, after changing to an ad-hoc network there are no further issues.  Sorry for the hassle KhaosT and thanks for your prompt responses dude.

**Comment by WouterPieper** [comment]
I've long been searching and trying, but it still does not work, maybe someone can help me
I have a Sonoff Switch which I want to put on and off with UDP command.

I read a lot about the firmware update, but if that's not necessary, I would not do that. because I have not enough knowledge in this area

I use a loxone miniserver to send UDP commands.
I need to know which UDP port is used.

I'm also need the ASCII udp commands that i can use to turn the sonoff switch ON and OFF.

I can test the commands with a udp sender on my windows computer.
For example i have another webrelais that already work.
I attached a picture of this example.
To turn OFF this webrelais i use port 1200 and ASCII command: u=2password\n
To turn ON this webrelais i use port 1200 and ASCII command: a=2password\n

is there anyone who can tell me which port and commands for ON and OFF i can use for the sonoff switch?
Or is it not possible to turn the switch ON and OFF on this way without updated the firmware of the sonoff switch?
![2 webrelais sample](https://cloud.githubusercontent.com/assets/24544292/21140842/5964b42c-c13a-11e6-893d-8ae74e730eef.JPG)
