### ISSUE TITLE
iPhone not detecting accessories from RasPi

### ISSUE THREAD

**Issue by finngaida** [KhaosT/HAP-NodeJS#30]
I have a similar issue, as discussed in #3 whereas when I run the server on my Mac everything works fine, the accessories show up and Siri commands get through.
Now after I got my Raspberry Pi B+ to run the server the console shoots me some warnings:

```
*** WARNING *** The program 'node' uses the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node>
*** WARNING *** The program 'node' called 'DNSServiceRegister()' which is not supported (or only supported partially) in the Apple Bonjour compatibility layer of Avahi.
*** WARNING *** Please fix your application to use the native API of Avahi!
*** WARNING *** For more information see <http://0pointer.de/avahi-compat?s=libdns_sd&e=node&f=DNSServiceRegister>
```

but then continues with `HAP-NodeJS starting...` and `TCP server accepting connection on port: 51826` and so on. Still my iPhone (as well as the iNet Bonjour Browser) won't detect any services.

**What I've tried so far:**
- Run `npm rebuild` again
- Reinstall `node-gyp`
- Reinstall `node` from the Heroku repo
- Restart the Pi
- Restart the router
- Restart the iPhone
- Clone the HAP repo again

I really don't know what I'm doing wrong and any help is highly appreciated.
Thanks for the effort.

### Update
When I run the server on my Mac and set up an accessory, cancel the server and run it on the Pi, I do see the iPhone's attempts on trying to verify the accessory, so there are commands coming through, the Pi is just not discoverable as it seems...

**Comment by KhaosT** [comment]
Those warnings can be ignored. Can you try to run [this](https://itunes.apple.com/us/app/inet-network-toolbox/id340793353?mt=8) on your iOS device and check if Bonjour discovery can see HAP service on your RasPi?

**Comment by finngaida** [comment]
Nope, it shows up my iPhone, Mac and Apple TV, and finds the RasPis as IP host, but not the HAP server.

**Comment by KhaosT** [comment]
@finngaida I'm not really familiar with avahi... Maybe try to google Raspberry Pi Bonjour discovery?

**Comment by finngaida** [comment]
I'm on it. Will let you know of any progress!

**Comment by elvisimprsntr** [comment]
Silly question.   Did you install avahi on the rpi per the wiki instructions?

**Comment by finngaida** [comment]
@elvisimprsntr Yes, I did. Via apt-get though, maybe I should try installing it from source...

**Comment by finngaida** [comment]
Okay, so hoping this might help anybody, I fixed the problem by being a little more patient and getting the RasPi it's internet from my Mac.
Previously the Pi was connected to the router via DLAN and the phone via WI-Fi obviously, so now I share my Mac's Wi-Fi connection via Ethernet to the Pi and everything works fine. (well mostly)

cheers

**Comment by nikriek** [comment]
I have the same problem. Even a direct connection to my route doesn't solve it. So, please reopen the issue, @finngaida's solution is not that production ready… :)

**Comment by KhaosT** [comment]
@nikriek but so far I can't reproduce this issue. If possible, can you share more detailed information about your network setup, linux distro you are using, Node.js version and avahi version? (I assume you are using RasPi?)

**Comment by nikriek** [comment]
I did a fresh install of the newest raspbian on my Pi, installed node v0.10.35 and avahi-deamon v0.6.31-2. My router is a Fritz!BOX 7270.

**Comment by nikriek** [comment]
It's now working! I just updated my router's firmware…
